### ISSUE TITLE
Create the file README.md

### ISSUE THREAD

**Issue by icaoberg** [pscedu/singularity-hyperfine#3]
Replace the strings

* `PACKAGE` with `hyperfine`,
* `VERSION` with `1.11.0`, and
* `LINK` with `https://github.com/sharkdp/hyperfine`

in the document below

https://gist.github.com/icaoberg/f9b78eef05c962445566dcc59d452b7d

and save this to a file named `README.md`.

**Comment by halbakri** [comment]
README.md created

**Comment by icaoberg** [comment]
@halbakri fix the issue with this file.

**Comment by halbakri** [comment]
README.md created
